#!/usr/bin/sh
# flake8: noqa

CHROMEDR=$(./chrome_update_parse.py)
echo $CHROMEDR
wget $CHROMEDR
unzip chromedriver-linux64.zip
rm chromedriver-linux64.zip

CHROMEDRIVER_DIR="/usr/local/share/chrome_driver"
CHROMEDRIVER_BIN="$CHROMEDRIVER_DIR/chromedriver"

sudo rm -rf $CHROMEDRIVER_DIR/*
sudo rm -rf $CHROMEDRIVER_BIN/*

sudo mkdir -p $CHROMEDRIVER_DIR
sudo mv "chromedriver" $CHROMEDRIVER_BIN
sudo chmod +x $CHROMEDRIVER_BIN
chromedriver --version